export const HANDLE_PRODUCTDETAIL = 'HANDLE_PRODUCTDETAIL'
export const HANDLE_CARTS = 'HANDLE_CARTS'
export const HANDLE_CARTS_QUANTITY = 'HANDLE_CARTS_QUANTITY'
export const DELETE_CART = 'DELETE_CART'